# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-css:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: './Streckenbuch.Server'
    - name: Install Node Libarys and build css
      run: | 
        cd ./Streckenbuch.Server
        npm ci
        npm run css:build
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Build new Style-CSS
